# Copyright 2025

name: "Copyright Check"
description: "Checks that all files contain 'Copyright'"

inputs:
  copyright_line:
    description: "Copyright"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Get changed files
      id: changed
      uses: tj-actions/changed-files@v47

    - name: Check for Copyright
      shell: bash
      run: bash ${{ github.action_path }}/entrypoint.sh
      env:
        CHANGED_FILES: ${{ steps.changed.outputs.all_changed_files }}
        COPYRIGHT_LINE: ${{ inputs.copyright_line }}
