# Copyright 2025

name: "Copyright Check"
description: "Checks that all files contain 'Copyright MyCompany'"

inputs:
  username:
    description: "User`s name"
    required: true
    default: "Вася"
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Get changed files
      id: changed
      uses: tj-actions/changed-files@v47

    - name: Check for Copyright
      shell: bash
      run: bash ${{ github.action_path }}/entrypoint.sh "${{ steps.changed.outputs.all_changed_files }}"
