# Copyright 2025

name: "Copyright Check"
description: "Checks that all files contain 'Copyright MyCompany'"

inputs:
  username:
    description: "User`s name"
    required: true
    default: "Вася"
runs:
  using: "composite"
  steps:
    - name: Run Bash script
      shell: bash
      run: bash ${GITHUB_WORKSPACE}//entrypoint.sh
