# Copyright 2025

name: "Copyright Check"
description: "Checks that all files contain 'Copyright MyCompany'"

inputs:
  username:
    description: "User`s name"
    required: true
    default: "Вася"
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Run JS action
      uses: ./js-action
      with:
        name: ${{ inputs.username }}
