# Copyright 2025

name: "Copyright Check"
description: "Checks that all files contain 'Copyright MyCompany'"

inputs:
  username:
    description: "User`s name"
    required: true
    default: "Вася"
runs:
  using: 'node20'
  main: "dist/index.js"
