# Copyright 2025

name: "Copyright Check"
description: "Checks that all files contain 'Copyright'"

inputs:
  copyright_line:
    description: "Copyright line"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed
      uses: tj-actions/changed-files@v47
#      with:
#        separator: "\n"

    - name: Get current year
      shell: bash
      id: copyright
      run: |
        if [ -n "${{ inputs.copyright_line }}" ]; then
          echo "line=${{ inputs.copyright_line }}" >> "$GITHUB_OUTPUT"
        else
          echo "line=Copyright 2013-$(date +%Y)." >> "$GITHUB_OUTPUT"
        fi

    - name: Check for Copyright
      shell: bash
      run: bash ${{ github.action_path }}/entrypoint.sh
      env:
        CHANGED_FILES: ${{ steps.changed.outputs.all_changed_files }}
        COPYRIGHT_LINE: "${{ steps.copyright.outputs.line }}"
